### ISSUE TITLE
custom validation message when email already exists and account is active

### ISSUE THREAD

**Issue by aksharj** [heartcombo/devise#5309]
Hi All,

I am sorry but i am not able to find a answer to this anywhere else so i am posting here.

I have a User model with email as the uniqueness key and also an `active` column on the user table which indicates if the account is active or not. The account becomes inactive after trial period ends unless the user signs up for one of the plans.

I am overriding the email already exists message like this 

```
en:
  activerecord:
    errors:
      models:
        user:
          attributes:
            email:
              taken: 'This email address has been used already. Please contact support if you would like more access'
```

However, I want to conditionally display different error message to the user when email is taken but account is active.

There are couple of scenarios:
1) Email taken and account is inactive: The above works and displays correct error message.
2) Email taken but account is active: I want to display a different error message like "Your account is still active, please sign in with link here"

So, I want to display different email taken messages conditionally.

Whats the correct way to handle this, any help will be really great. Thanks.
