### ISSUE TITLE
Transfer Rails 7.0.0.alpha2, get "NoMethodError (undefined method `failure_app' for nil:NilClass)"

### ISSUE THREAD

**Issue by HeppokoNeet** [heartcombo/devise#5427]
## Environment

- Ruby **[3.0.0]**
- Rails **[7.0.0.alpha2]**
- Devise **[4.8.0]** ("gem 'devise', git: 'https://github.com/heartcombo/devise', branch: 'main'" in Gemfile)

## Current behavior

Curentlly I've transfered my environment following the below.

|Previous version|New version|
|:--|:--:|
|Rails 5.12|Rails 7.0.0.alpha2|
|Ruby 2.4.1|Ruby 3.0.0|
|Devise 4.3.0|Devise 4.8.0|

I use rails_admin for account management.
But When my environment has transfered, I got  "NoMethodError (undefined method `failure_app' for nil:NilClass)" as error.
Before transferring,  rails_admin was totally fine. 

I checked `Devise.mappings` in rails console, there is no `:admin_user`.
I think `rails_admin.rb` is fine.
```
RailsAdmin.config do |config|
  ### Popular gems integration

  ## == Devise ==
  config.authenticate_with { warden.authenticate! scope: :admin_user }
  config.current_user_method(&:current_admin_user)

  ## == Cancan ==
  config.authorize_with :cancancan

  ## == Pundit ==
  # config.authorize_with :pundit

  ## == PaperTrail ==
  config.audit_with :paper_trail, 'AdminUser', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  ## == Gravatar integration ==
  ## To disable Gravatar integration in Navigation Bar set to false
  # config.show_gravatar = true

  RailsAdmin.config do |c|
    c.actions do
      dashboard { statistics false }
  end
end

module RailsAdmin
  module Config
    module Fields
      module Types
        class Datetime < RailsAdmin::Config::Fields::Base
          register_instance_option :date_format do
            :default
          end
        end
        class Date < RailsAdmin::Config::Fields::Types::Datetime
          register_instance_option :date_format do
            :default
          end
        end
      end
    end
  end
end
...
```
And I post an issue in [railsadminteam / rails_admin](https://github.com/railsadminteam/rails_admin/issues/3444).
They said it's issue of devise setting.

I think the problem is one of the following.

- **Part of devise setting was chenged from a few years ago**
- **The bug of devise**

I leave my devise setting.

`devise.rb`
```
Devise.setup do |config|
  config.secret_key =
    'secret_key'
  config.mailer_sender = 'example@example.com'
  require 'devise/orm/active_record'
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 12
  config.reconfirmable = true
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
  config.timeout_in = 3.hours
  config.reset_password_within = 6.hours
  config.sign_out_via = :delete
end
```

`routes.rb`

```
...
 devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations',
             }
 mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
```

`devise_helper.rb`
```
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end
```

`user.rb`
```
...
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable
```

`devise.en.yml`
```
# Additional translations at https://github.com/heartcombo/devise/wiki/I18n

en:
  devise:
    confirmations:
      confirmed: "Your email address has been successfully confirmed."
      send_instructions: "You will receive an email with instructions for how to confirm your email address in a few minutes."
      send_paranoid_instructions: "If your email address exists in our database, you will receive an email with instructions for how to confirm your email address in a few minutes."
    failure:
      already_authenticated: "You are already signed in."
      inactive: "Your account is not activated yet."
      invalid: "Invalid %{authentication_keys} or password."
      locked: "Your account is locked."
      last_attempt: "You have one more attempt before your account is locked."
      not_found_in_database: "Invalid %{authentication_keys} or password."
      timeout: "Your session expired. Please sign in again to continue."
      unauthenticated: "You need to sign in or sign up before continuing."
      unconfirmed: "You have to confirm your email address before continuing."
    mailer:
      confirmation_instructions:
        subject: "Confirmation instructions"
      reset_password_instructions:
        subject: "Reset password instructions"
      unlock_instructions:
        subject: "Unlock instructions"
      email_changed:
        subject: "Email Changed"
      password_change:
        subject: "Password Changed"
    omniauth_callbacks:
      failure: "Could not authenticate you from %{kind} because \"%{reason}\"."
      success: "Successfully authenticated from %{kind} account."
    passwords:
      no_token: "You can't access this page without coming from a password reset email. If you do come from a password reset email, please make sure you used the full URL provided."
      send_instructions: "You will receive an email with instructions on how to reset your password in a few minutes."
      send_paranoid_instructions: "If your email address exists in our database, you will receive a password recovery link at your email address in a few minutes."
      updated: "Your password has been changed successfully. You are now signed in."
      updated_not_active: "Your password has been changed successfully."
    registrations:
      destroyed: "Bye! Your account has been successfully cancelled. We hope to see you again soon."
      signed_up: "Welcome! You have signed up successfully."
      signed_up_but_inactive: "You have signed up successfully. However, we could not sign you in because your account is not yet activated."
      signed_up_but_locked: "You have signed up successfully. However, we could not sign you in because your account is locked."
      signed_up_but_unconfirmed: "A message with a confirmation link has been sent to your email address. Please follow the link to activate your account."
      update_needs_confirmation: "You updated your account successfully, but we need to verify your new email address. Please check your email and follow the confirmation link to confirm your new email address."
      updated: "Your account has been updated successfully."
      updated_but_not_signed_in: "Your account has been updated successfully, but since your password was changed, you need to sign in again."
    sessions:
      signed_in: "Signed in successfully."
      signed_out: "Signed out successfully."
      already_signed_out: "Signed out successfully."
    unlocks:
      send_instructions: "You will receive an email with instructions for how to unlock your account in a few minutes."
      send_paranoid_instructions: "If your account exists, you will receive an email with instructions for how to unlock it in a few minutes."
      unlocked: "Your account has been unlocked successfully. Please sign in to continue."
  errors:
    messages:
      already_confirmed: "was already confirmed, please try signing in"
      confirmation_period_expired: "needs to be confirmed within %{period}, please request a new one"
      expired: "has expired, please request a new one"
      not_found: "not found"
      not_locked: "was not locked"
      not_saved:
        one: "1 error prohibited this %{resource} from being saved:"
        other: "%{count} errors prohibited this %{resource} from being saved:"
```

I really need  helps....
Looking forward for your reply.

Thank you.
